#!/bin/bash

##
# fcow - command
#
# @author Bruno Castro Garcia
# @author Angel Ruiz Fernandez
#
# @version 1.0
# @since April 2022


VERSION=1.0


### "Pre-program"
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	cat "/usr/local/share/fcow/HELP" |lolcat
	exit
elif [[ "$1" == "-v" || "$1" == "--version" ]]; then
	echo $VERSION |lolcat
	exit
fi;


### Actual program

# Defaults
cowfile="default"
sot="say"
bdgpstwy=""

while [[ "$#" -gt 0 ]]; do
	case $1 in
		-r|--random)
			# Get path of cow files
			COWS=$(cowsay -l |grep "Cow files in " |awk 'match($0,/\/.*\/[^ ]*/){print substr($0,RSTART,RLENGTH-1)}')

			# Override defaults to RANDOM stuff
			cowfile=$(ls $COWS/*.cow |shuf -n 1)
			sot=$(echo -ne "say\nthink" |shuf -n 1)
			bdgpstwy="-bdgpstwy"
		shift;;

		# Future options
	esac
	shift
done;


### GO!
fortune -a |cow$sot -f $cowfile $bdgpstwy |lolcat
