name: Create debian package

on: [push, pull_request]

env:
  pkg_name: fcow_1.2-${{GITHUB_RUN_NUMBER}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create package structure
        run: |
          mkdir ${{pkg_name}}
          cd ${{pkg_name}}
          mkdir -p DEBIAN usr/local/bin usr/local/man/man6 usr/local/share/fcow

      - name: Copy stuff inside
        run: |
          cp deb_control ${{pkg_name}}/DEBIAN/control
          cp src/* ${{pkg_name}}/usr/local/bin/
          chmod +x ${{pkg_name}}/usr/local/bin/*
          cp share/* ${{pkg_name}}/usr/local/share/fcow/
          cp man/* ${{pkg_name}}/usr/local/man/man6/

      - name: Create deb package
        run: dpkg-deb -Zxz --build ${{pkg_name}}

      - name: Upload deb as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{pkg_name}}.deb
          path: ${{pkg_name}}.deb
